spring:
  application:
    name: construct-manager-backend

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/construct_manager?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

    # HikariCP Configuration for high performance
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
      pool-name: ConstructManagerHikariCP

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: false
        # Performance optimizations
        jdbc:
          batch_size: 25
          fetch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        # Second level cache - disabled to fix startup error
        cache:
          use_second_level_cache: false
          use_query_cache: false

  # Redis Configuration disabled to fix connection issues
  # data:
  #   redis:
  #     host: localhost
  #     port: 6379
  #     password:
  #     timeout: 2000ms
  #     lettuce:
  #       pool:
  #         max-active: 8
  #         max-idle: 8
  #         min-idle: 0

  # Cache Configuration - using simple in-memory cache instead of Redis
  cache:
    type: simple
    cache-names: projects,units,categories,teams
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

# Logging Configuration
logging:
  level:
    com.constructmanager: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Custom Application Properties
app:
  jwt:
    secret: 9a4f2c8d3b7e1a5f2c8d3b7e1a5f2c8d3b7e1a5f2c8d3b7e1a5f2c8d3b7e1a5f
    expiration: 86400000 # 24 hours

  pagination:
    default-page-size: 20
    max-page-size: 100

  cache:
    ttl:
      projects: 300 # 5 minutes
      units: 600 # 10 minutes
      categories: 900 # 15 minutes
      teams: 1800 # 30 minutes

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized